### ISSUE TITLE
Use docker-compose to the furthest possible extent

### ISSUE THREAD

**Issue by mtbentley** [hacsoc/case-acm-server#1]
We will still need some bash glue (mostly for startup and networking), but we should define as much as possible within docker-compose.

Also look into using systemd for startup of containers and networking.

**Comment by ZJaffee** [comment]
I'm not sure if you have an architectural plan in mind for how containers should communicate, but if you have one, feel free to share and I could work on this issue.

**Comment by mtbentley** [comment]
I've done a bit of work on this today, here is what I have, using the Jolly Advisor as a model:
The yaml file:

``` yaml
jolly:
  image: hacsoc/jolly-advisor
  links:
    - jollypostgres
  env_file: jolly.env

jollypostgres:
  image: postgres
  volumes: 
    - /var/lib/postgres/data
  env_file: ./jollypostgres.env
```

The big problem is getting a unique IP address on each container.  Right now, it relies on creating new interfaces and then some iptables shenanigans.  Since there has been some progress with network namespaces in the past few months, another option is:

``` bash
sudo ip link add jolly link eth0 address <MAC ADDRESS> type macvlan mode bridge
PID=`docker inspect -f '{{.State.Pid}}' acm_jolly_1`
sudo ln -s /proc/${PID}/ns/net /var/run/netns/${PID}
sudo ip link set jolly netns ${PID}
sudo ip netns exec ${PID} ip r del default
sudo ip netns exec ${PID} dhcpcd jolly & echo $! > jollydhcp.pid
```

And then `sudo kill -9 $(cat jollydhcp.pid)` on exit.

These commands create a fake interface to get an IP from Case, put it in the same network namespace as the container, and get the IP address and setup the routes.  
It's still not a pure docker-compose solution, but it's closer, and get's rid of my awful bash script that's currently tracking dependencies.  The only things that still need to be worked out are the volumes (right now each container just mounts a file to a specific location, but this gives us a bit more flexibility), and creating a proper startup script to manage it (systemd should be useful for this, and _might_ be able to do some of the network setup too).

**Comment by ZJaffee** [comment]
first off, in the yaml file you will want to add the following for each of the different containers

> port  #x:#x

for example for postgres the port you generally use is 5432
so you would write the line:

> port 5432:5432

to add an ip address to this you would add the ip address right in front of the first port listed there
so what you could then do is write 

> port 10.0.2.2:5432:5432

I would take the command from case, and generate the string and place it as I showed above.

However, if you simply mean port numbers and not IP addresses, this problem is really easy to solve, otherwise you'll need to write some bash code.

If what I'm saying isn't directly related to what you mean let me know, because I might just be confused with what your problem is.

**Comment by mtbentley** [comment]
That doesn't directly address the issue. First, the port isn't needed for postgres because communication between containers is open by default (chech the docker docs regarding networking for more info).  

Second (and this is the bigger issue) to get a .case.edu subdomain, you need to register a mac address.  Once it's registered, we create a MACVLAN virtual networking device with that mac, and then use network namespaces (netns) to put that device in the container.  This way, all traffic to that IP (and subdomain) go directly to that container (and the app in it).  

Docker{,-compose} has no built in way to do this*, so it'll require a bash wrapper (which will also help with creating services with systemd).

*docker libnetwork might help, but I'm not sure how much work that would be

**Comment by ZJaffee** [comment]
I thought you wanted containers to be addressed from an outside source, as in the website is spun up from within one of the containers. If thats what you want to do then adding the port as above would allow you to go to that port number on the localhost of the machine you are running docker from. I assume if you attach it to a unique IP address, it would then be able to reference that MAC address via the IP or subdomain. I also think that adding the port 3000:3000 to the jolly advisor container would be smart since it would then be accessible from localhost:3000.

I don't think you will be able to have a docker compose solution to this purely, but I think it will be a useful tool for when people want to set up their own apps. Possibly by modifying the definition of docker compose so that it runs a bash script that adds the line that references their IP address to the *.yml file for each of the containers made by docker-compose, before running the traditional definition of docker-compose. Also, while requiring everyone who wants to host a website to write a docker-compose file in order to generate it. Then hopefully they don't make a mess of their environment and they know how to clean it up.

However, this is assuming you think docker-compose is the best way for people to configure their own web-apps to be on the server. 

I don't think libnetwork will be of value, and also it isn't stable currently so you would need to be careful if you try and use it, especially when its unclear how users will be interacting with the system.

**Comment by ZJaffee** [comment]
You could also use https://github.com/docker/libkv to pair either a users caseId or some UUID generated with their personal IP address.

**Comment by ZJaffee** [comment]
Another thing that I just found is that we could customize the builds based off of what type of app they are building, the docs for docker-compose have examples for django and rails that their native tools to link the IP address to the port number.

**Comment by mtbentley** [comment]
Closed with the latest commits which add actual useful stuff.
